vyperlang/titanoboa

boa/interpret/expr.py
**What I did**
- Handle `BoolOp` nodes in a similar fashion to `BinOp`.
=> feat: add boolop

pyproject.toml
=> fix: import of `boa.vyper` module

README.md
Add instructions to fix issuer. #16
=> doc: troubleshoot local vyper installation

README.md
Add forking mainnet example on README.md
=> Add forking example

README.md
had some trouble finding the docs
=> chore: add link to docs to README

README.md, docs/source/api.rst
Fix #39.
I think there is not much to write about since internal functions have the same API as external functions.
=> docs: internal functions

.readthedocs.yaml, docs/source/test.rst
=> [wip] add notes about pytest

.github/PULL_REQUEST_TEMPLATE.md, boa/vyper/contract.py
- Check if there is a docstring, when no docstring is present the attribute is undefined
- Test should pass
=> Check if there is a doc_string

docs/source/api.rst
raw_call is very useful, but I didn't find it until I went looking in the source code. Added to docs.
Years of unceasing training in creating pull requests.
Eyeball comparison with code in [environment.py](https://github.com/vyperlang/titanoboa/blob/4d75e780382a9cf4cb537847e403e8790482dbe5/boa/environment.py#L646)
There's a changelog?
- Added documentation for `raw_call`
=> Add raw_call to docs

boa/explorer.py, tests/integration/fork/test_from_etherscan.py, tests/integration/network/anvil/conftest.py, tests/integration/network/anvil/test_network_env.py
Fixed the integration tests
Disabling prefetching in anvil integration tests
Tests should pass
N/A
=> fix: disable prefetch for anvil tests

boa/vm/fork.py
not sure if this ever can ever happen where we apply part of the trace and then find out it is broken in the middle of the trace, but clean the state anyways for hygiene.
=> chore: clean state properly in try_prefetch_state

docs/source/api.rst
=> docs: added alias function description

boa/integrations/jupyter/jupyter.js, boa/integrations/jupyter/utils.py
=> Send service prefix from backend

boa/integrations/jupyter/utils.py, boa/interpret.py, tests/integration/fork/test_from_etherscan.py
=> fix: unit and integration tests

boa/contracts/vyper/vyper_contract.py, boa/network.py
=> add evm version capabilities checker to NetworkEnv

.github/workflows/integration.yaml
- Tried to fix the integration tests merge
=> fix[test]: integration test

boa/network.py
=> add debug_tt suppression

boa/contracts/base_evm_contract.py, boa/contracts/vyper/vyper_contract.py, boa/environment.py, boa/network.py, tests/integration/fork/test_logs.py, tests/unitary/test_logs.py, tests/unitary/test_reverts.py
Fixes #226 
- Exposed the logs created during contract creation
- Exposing the environment's last computation
- Tests should now pass
- fix: expose constructor logs
=> feat: handle constructor logs and exceptions

FUNDING.json
Add a json file to verify Vyper on https://www.drips.network/app/projects
=> Add FUNDING.json for Drips

.env.unsafe.example, .gitignore, CONTRIBUTING.md
Adding contributing documentation.
By going through the process of contributing and documenting it.
Try it yourself. 
- Added `CONTRIBUTING.md`
=> add contributing.md file

boa/coverage.py, boa/environment.py, boa/network.py, docs/source/testing.rst
=> fix: coverage paths

boa/contracts/base_evm_contract.py, boa/contracts/vyper/vyper_contract.py, boa/environment.py, boa/profiling.py, boa/test/plugin.py, docs/source/testing.rst, tests/unitary/test_gas_profiling.py
=> fix: gas profile when non-VyperContracts exist in the environment

boa/environment.py
an existing test that was failing, now passes
=> fix coverage in the presence of ABIContract

.github/workflows/release-pypi.yml
mostly copied over from the vyper one (commit 9a208a6950900f)
=> chore: add release workflow for titanoboa

pyproject.toml
=> bump version to 0.2.2

.github/workflows/release-pypi.yml
=> fix: build script in gh release action

CONTRIBUTING.md
Added a line about how users need to also install regular dependencies.
- Improved `CONTRIBUTING.md`
=> fix: updated contributing docs so users can install dependencies

boa/interpret.py, tests/unitary/utils/test_cache.py
Use the already available caching system also to support contracts deployed by VVM
Unit tests
=> feat: cache vvm contracts

CONTRIBUTING.md, boa/__init__.py, boa/util/open_ctx.py, tests/unitary/test_boa.py
=> refactor: generalize the TmpEnvMgr context manager

boa/contracts/vvm/vvm_contract.py
=> fix dead **kwargs and use of blueprint_preamble kwarg

pyproject.toml
=> update version to 0.2.4

tests/integration/network/sepolia/test_sepolia_env.py
=> simplify a test

boa/contracts/vyper/vyper_contract.py, tests/unitary/contracts/vyper/test_vyper_contract.py
this was a regression in 287523f7c176d14ade84c9053aacd28a33555289
add a regression test
=> fix stomp()

boa/network.py
=> fix: filename can be Path

boa/environment.py
=> update error message for time travel

tests/integration/fork/test_gas_profiling_fork.py
=> add gas profile tests for fork mode

boa/util/abi.py, tests/unitary/contracts/abi/test_abi.py
fix is in https://github.com/skellet0r/eth-stdlib/pull/22, but not sure
when it can be released. until then, monkey patch the vendored fix.
=> fix: tuple decoding in eth-stdlib

tests/unitary/contracts/vvm/test_vvm.py
=> add tests for contract._computation after deploy

boa/util/sqlitedb.py
when multiple boa forks are executed, they can get into a write contention scenario as in 
https://github.com/vyperlang/titanoboa/actions/runs/12982658964/job/36202772577?pr=378#step:6:277
(copy/paste of logs):
```
/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/boa/network.py:173: in __init__
self._reset_fork()
/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/boa/network.py:506: in _reset_fork
self.fork_rpc(self._rpc, reset_traces=False, block_identifier=block_identifier)
/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/boa/environment.py:95: in fork_rpc
self.evm.fork_rpc(rpc, block_identifier, debug=debug, **kwargs)
/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/boa/vm/py_evm.py:424: in fork_rpc …
```
=> fix contention on sqlitedb creation

boa/util/sqlitedb.py
apparently, executescript() cannot operate if there is an active lock (even if it is just executing pragmas).
=> fix sqlite initialization in multithreaded environment

boa/network.py
some RPCs don't support the "pending" block.
=> add estimate_gas_block_identifier to TransactionSettings object

pyproject.toml
=> update version to 0.2.6

boa/contracts/abi/abi_contract.py, boa/contracts/vyper/vyper_contract.py, boa/environment.py, boa/network.py, tests/integration/network/anvil/test_network_env.py, tests/integration/network/sepolia/test_sepolia_env.py, tests/unitary/test_simulate.py
=> add simulate= kwarg

pyproject.toml
=> chore: bump version to 0.2.7

docs/api/load_contracts.md, docs/api/vyper_contract/function_calls.md, docs/api/vyper_contract/overview.md, docs/deployments.md, docs/guides/advanced_features.md, docs/guides/performance_optimization.md, docs/guides/testing/gas_profiling.md
=> feat[docs]: document deployments db

mkdocs.yml
grepped and added a p
using neovim
by looking
N/A
=> docs: fix typo

boa/network.py
=> feat: add prague detection to capabilities checker
