- boa/contract.py
- pyproject.toml
- tests/sim_veYFI.py
Partial solution for #21 by replacing `eth_abi` with `eth_stdlib` for encoding and decoding.
One issue is that `eth_stdlib` requires python 3.10, but Vyper targets python 3.8 and above.
> fix: replace `eth_abi` with `eth_stdlib`

- boa/environment.py
- boa/vyper/contract.py
- docs/source/api.rst
- tests/unitary/test_injects.py
- tests/unitary/test_time_travel.py
easy option to mine a single block (with a user specified block timestamp, set to default at 12 sec: or 11?)
also added block_timestamp and block_number properties.
> add `boa.env.time_travel()`

- boa/vm/fork.py
When using boa with a ganache (v7.7.2) local fork, I ran into the following error when trying to retrieve a value:
This happens because recent version of ganache return "0x" for empty values instead of "0x0" or "0x0000000000000000000000000000000000000000000000000000000000000000". 
This fix handles this edge case
> Handle empty hex strings ('0x') returned by latest ganache versions

- boa/vyper/contract.py
Fixes #53
Just handled the case where child_obj is None because the contract for which the external call failed is not part of the environment's contracts
> Handle edge-case where contract lookup in environment fails

- boa/vyper/contract.py
#57
Recurse when the contract is unknown and fill in the missing stack frames with the unknown contract's address.
> Handle stack traces with unknown contracts

- pyproject.toml
There is a breaking change in `eth_abi` where `decode_single` / `encode_single` has been deprecated after `3.0.1`, and the types and values for decode/encode need to be provided as a list - e.g. `encode(["uint256"], [1])` instead of `encode("uint256", 1)` previously.
This PR pins `eth_abi` to `3.0.1` to resolve this issue. In the long term, `eth_abi` can be dropped once support for python 3.9 and 3.9 is dropped and we can switch to `eth-stdlib` entirely.
> chore: pin `eth_abi` dependency

- boa/__init__.py
- boa/debugger.py
- boa/vyper/decoder_utils.py
This small PR fixes the following error:
```
venv/lib/python3.10/site-packages/boa/vyper/contract.py:891: in __call__
return self.contract.marshal_to_python(computation, typ)
venv/lib/python3.10/site-packages/boa/vyper/contract.py:620: in marshal_to_python
self.handle_error(computation)
venv/lib/python3.10/site-packages/boa/vyper/contract.py:641: in handle_error
raise BoaError(self.vyper_stack_trace(computation))
venv/lib/python3.10/site-packages/boa/vyper/contract.py:648: in vyper_stack_trace
ret = StackTrace([ErrorDetail.from_computation(self, computation)])
venv/lib/python3.10/site-packages/boa/vyper/contract.py:175: in from_computation
frame_detail = contract.debug_frame(computation)
venv/lib/python3.10/site-packages/boa/vyper/contract.py:522: in debug_frame
frame_detail[k] = …
```
> fix: decoding of bytesM types

- boa/profiling.py
- boa/vyper/ast_utils.py
- boa/vyper/contract.py
This PR applies a band-aid patch to the following error:
```
@given(
>       dx=strategy("uint256", min_value=10**10, max_value=100 * 10**18),
j=strategy("uint8", min_value=0, max_value=1),
)
tests/unitary/pool/test_callback.py:42: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
venv/lib/python3.10/site-packages/boa/test/plugin.py:23: in f
t(*args, **kwargs)
tests/unitary/pool/test_callback.py:51: in test_revert_good_callback_input_eth
zap.good_exchange(2, j, dx, 0, True, value=dx)
venv/lib/python3.10/site-packages/boa/vyper/contract.py:894: in __call__
return self.contract.marshal_to_python(computation, typ)
venv/lib/python3.10/site-packages/boa/vyper/contract.py:623: in …
```
> Fix: fn node getter

- boa/__init__.py
- boa/environment.py
- boa/precompile.py
fixes #38 
Implements a decorator that handles the abi encoding and decoding of precompile arguments and return values
```python
@boa.precompile("def huff(filename: String[128]) -> address")
def huff(filename: str):
compilation_process = subprocess.run(["huffc", "-b", filename], capture_output=True)
contract_address = boa.env.generate_address()
contract_bytecode = binascii.unhexlify(compilation_process.stdout)
boa.env.deploy_code(deploy_to=contract_address, bytecode=contract_bytecode)
return contract_address
HUFF_PRECOMPILE_ADDRESS = bytes.fromhex("0000000000000000000000000000000068756666") # "huff" in bytes
register_precompile(HUFF_PRECOMPILE_ADDRESS, huff)
```
abi encoding and decoding had to be handled in the precompile definition
```python
def compile_huff_code(computation): …
```
> Implement precompile decorator

- boa/environment.py
When running coverage in complex scenarios the stack will overflow with a stdout similar to
```
File "/Users/controlc/Library/Caches/pypoetry/virtualenvs/minimal-repro-NwtGl1oq-py3.10/lib/python3.10/site-packages/boa/environment.py", line 576 in _hook_trace_computation
File "/Users/controlc/Library/Caches/pypoetry/virtualenvs/minimal-repro-NwtGl1oq-py3.10/lib/python3.10/site-packages/boa/environment.py", line 576 in _hook_trace_computation
File "/Users/controlc/Library/Caches/pypoetry/virtualenvs/minimal-repro-NwtGl1oq-py3.10/lib/python3.10/site-packages/boa/environment.py", line 576 in _hook_trace_computation
```
Upon investigation I found 2 potential culprits, first being 
`child_contract` in the hook_trace function can sometimes be empty bytes resulting in this format error for the …
> Fix StackOverflow When Running Coverage

- docs/source/api.rst
- Add `compiler_args` to the documentation of `loads`, `load_partial` and `loads_partial`.
- Add `dedent` to the documentation of `loads_partial`
> docs: add kwargs to API reference

- boa/vyper/contract.py
If an error is raised in a method not specified in the ABI, boa currently crashes with a KeyError.
Instead of crashing we can still provide some stack trace for the user without a method name.
Given https://github.com/vyperlang/titanoboa/issues/106 it's sometimes currently not possible to include a full ABI.
> Avoid KeyError for unspecified ABI traces

- .pre-commit-config.yaml
- boa/network.py
- docs/source/coverage.rst
There is a conflict between `black` and `isort` that is causing pre-commit hooks to always fail
`black` changes the file and `isort` changes it back to the original. The result is the hook fails and the code is not changed.
In this PR I updated the pre-commit config to the latest versions and changed the `isort` line length to match what `black` expects
> Fix pre-commit checks

- boa/vyper/decoder_utils.py
- tests/unitary/test_reverts.py
I experienced issues when boa tried to print debug frames before a specific dyn array is initialized.
The memory might contain a very large length, which causes boa to loop forever.
I created a minimal reproduction in unit test and fixed it by handling unexpected array lengths.
Tests included
Fix endless loops when debugging uninitialized variables
> fix debug frames for uninitialized variables

- .github/workflows/main.yaml
- boa/environment.py
- boa/vyper/contract.py
- boa/vyper/decoder_utils.py
- tests/unitary/test_reverts.py
- Save the contract `repr` with the computation in case of an error
- Use this value to show the storage state when the computation errored
- This should fix #92
- Investigated how py-evm handles the snapshots
- However, the data gets completely deleted after revert. To save all the [deleted data](https://github.com/ethereum/py-evm/blob/d625109bd92ab9a811c9ab64d375448b3fe7aecf/eth/db/account.py#L438-L444) would be quite cumbersome
- Instead of saving the whole journal, it makes more sense to only save the data we need when we need it
- Therefore I only extract the `repr(contract)` before the revert, as this is the information used
- Alternatively we could extract more data at this point (e.g. `storage.dump()`)
- The implementation is in the `environment` as this is specific to py-evm
- …
> Display storage dump with state before revert

- boa/integrations/jupyter/browser.py
- boa/integrations/jupyter/jupyter.js
- tests/unitary/jupyter/test_browser.py
Closes #128
~~Depends on https://github.com/vyperlang/titanoboa/pull/124~~
Allow signing typed data using BrowserSigner
- Created the `sign_typed_data` method in the BrowserSigner.
- Created the `signTypedData` front-end callback
- Added a test
Try in a notebook:
```
!pip install git+https://github.com/DanielSchiavini/titanoboa.git@128/sign-typed-data
from boa.integrations.jupyter import BrowserSigner
BrowserSigner().sign_typed_data(....)
```
Allow signing typed data in JupyterLab/Colab using BrowserSigner
> Sign typed data using BrowserSigner

- boa/integrations/jupyter/browser.py
- boa/integrations/jupyter/jupyter.js
Changed the browser signer to use sendTransaction instead of signTransaction.
The send transaction is [not supported](https://github.com/DanielSchiavini/titanoboa/blob/6d67bda184b257bf3c79d4a19f8b74929ac4a8d8/boa/network.py#L414) on metamask.
- Changed the JS call
- Added the tx_hash to an array to call getTransactionReceipt
- Deploy a contract with metamask
- Added support to sign transactions in metamask
> Use sendTransaction instead of signTransaction

- boa/integrations/jupyter/handlers.py
- boa/integrations/jupyter/jupyter.js
Jupyter replays all the `display` calls when the page is reloaded. Therefore, the JavaScript wallet triggers may run again when the page is loaded or shared with other people.
- Introduced a check to omit running JS code when the page reloads
- Added a new endpoint to check whether the memory object is still valid
- Save a notebook including the cell outputs. For example, the output of a contract deployment.
- Reload the page: No JS calls should be made. For example, the wallet should not ask to sign the transaction again
- Fixed cell replays in JupyterLab
> Do not trigger wallet on page reload

- boa/interpret.py
- tests/unitary/test_import_overloading.py
override `import` statement so that it looks for `.vy` files and tries to load them as `VyperDeployer`s.
> implement "native" imports for boa

- .github/workflows/main.yaml
Changed the pipeline to use the `pull_request_target`, so users with push access may run the pipeline using secrets.
By using a small github script that calls [getCollaboratorPermissionLevel](https://docs.github.com/en/rest/collaborators/collaborators?apiVersion=2022-11-28#get-repository-permissions-for-a-user)
Make a PR targetting this branch (pipeline) in my fork. The integration pipeline should raise an error.
[Here is an example](https://github.com/DanielSchiavini/titanoboa/actions/runs/7845528585/job/21410159640) of a successful check targeting this branch.
N/A
> ci: Use `pull_request_target` with permissions check

- boa/environment.py
- boa/vm/fork.py
Simplified the way we create the AccountDBFork by using a class factory.
Creating a new class on-the-fly
Everything should work the same
N/A
> Create an AccountDB class on-the-fly

- boa/contracts/abi/abi_contract.py
- tests/integration/fork/test_abi_contract.py
- tests/unitary/test_abi.py
Allow special args in overloaded ABI methods
- Matching the arguments of `ABIFunction` in the `ABIOverload` call
- Tests are included
- Fixed special arguments (value, gas, sender) passed to overloaded ABI functions
> fix: Allow special args in overloaded ABI methods

- boa/environment.py
- boa/vm/fork.py
- boa/vm/gas_meters.py
- tests/integration/fork/test_abi_contract.py
- Storage does not show deleted slots as though they are not registered. Thence data is fetched from RPC and leads to errors.
- According to [EIP2200 specification](https://eips.ethereum.org/EIPS/eip-2200) call-frame refund counters can go negative, so I changed strategy to appropriate.
- Added more precise checks along with autocaching values.
- Set strategy at initialisation.
There is a test flipping slot to zero and back.
> Fix: storage read and refund strategy

- boa/integrations/jupyter/browser.py
Allowed chain_id to be passed as integer as that's what users are expecting.
- Encoding/decoding the hex string
- `boa.env.set_chain_id(1)` should actually work
- Allow integers to be passed to boa.env.set_chain_id`
> feat: chain_id as integer

- boa/interpret.py
fix import error messages by fixing compliance with the metapath protocol. instead of always returning a module loader which errors out if it can't find a module, return None early (from find_module) if we can't find the module. this lets the system fall back to the system error handling for not-found modules.
try importing a non-existent module with and without this patch. the results should look like:
(unpatched):
```python
>>> import boa
>>> import asdlkfj
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/charles/titanoboa/boa/interpret.py", line 48, in load_module
raise ImportError(fullname)
ImportError: asdlkfj
>>> from requests import asldkjfasdf
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File …
```
> fix: import error messages

- boa/contracts/abi/abi_contract.py
- boa/contracts/vyper/vyper_contract.py
- boa/environment.py
- boa/interpret.py
- boa/test/strategies.py
- boa/util/abi.py
- tests/unitary/jupyter/test_browser.py
- tests/unitary/strategy/test_address.py
- tests/unitary/test_blueprints.py
it was previously inheriting from str so that the abi encoder/decoder could work, but now we have a custom implementation which handles Address. change the inheritance and remove explicit usages of `\.canonical_address`.
fix #136
> refactor: Address inherit from bytes

- boa/contracts/abi/abi_contract.py
- Added prepare_calldata methods to ABIFunction and ABIOverload
- Extracting the existing code into those functions
- Everything should still work
- Add support for prepare_metadata methods in ABI functions
> feat: Extract prepare_calldata method

- .github/workflows/.pre-commit-config.yaml
- .github/workflows/integration.yaml
- .github/workflows/main.yaml
Simplify the pipeline and try to fix build issues
by merging head into base instead of base into head.
Hopefully this should fix the pipelines. However the errors in masters are not easily reproduced
N/A
> fix[ci]: integration pipeline merge commit

- boa/environment.py
- tests/unitary/test_coverage.py
Fix a `RecursionError: maximum recursion depth exceeded in comparison` happening while running tests with code coverage enabled.
```
.venv/lib/python3.11/site-packages/boa/contracts/vyper/vyper_contract.py:1007: in __call__
computation = self.env.execute_code(
.venv/lib/python3.11/site-packages/boa/environment.py:709: in execute_code
self._hook_trace_computation(ret, contract)
.venv/lib/python3.11/site-packages/boa/environment.py:726: in _hook_trace_computation
self._hook_trace_computation(computation, child_contract)
.venv/lib/python3.11/site-packages/boa/environment.py:726: in _hook_trace_computation
self._hook_trace_computation(computation, child_contract)
.venv/lib/python3.11/site-packages/boa/environment.py:726: in _hook_trace_computation
self._hook_trace_computation(computation, …
```
> fix RecursionError tracing child computations

- boa/integrations/jupyter/jupyter.js
- tests/unitary/test_coverage.py
- Fixed callback URL when opening in lab view, i.e. `https://try.vyperlang.org/user/{user}/lab/workspaces/auto-L/tree/{file}.ipynb` instead of the notebook URL `https://try.vyperlang.org/user/{user}/notebooks/{file}.ipynb`
- Check if we are in lab view, if so recurse 3 directories
- Added `async` to `rpc` so the exception is displayed properly
- Open the notebook in the 2 views mentioned, it should work the same.
- Fixed jupyter plugin lab view
> fix: lab view URL

- boa/contracts/abi/abi_contract.py
- boa/contracts/vyper/vyper_contract.py
- tests/integration/fork/test_from_etherscan.py
- tests/unitary/test_abi.py
- Added _abi field to ABIContract, so it can be available for later use, e.g. when using `fetch_from_etherscan`
- Moving the function creation to the ABIContract
- The ABI is still available after the contract is created
N/A
> Keep abi in ABIContract

- pyproject.toml
ran into this when upgrading to python 3.12. seems like it's a regression in eth-rlp dependency specification
> chore: update requirements

- boa/network.py
- tests/unitary/test_time_travel.py
Fix UnboundLocalError: local variable 'snapshot_id' referenced before assignment
This was caused by a typo, the property `block_id` was removed in #134. Another typo broke the time travel tests.
Used the correct `block_number` property
Unit tests should pass
Fix UnboundLocalError: local variable 'snapshot_id' referenced before assignment
> fix: local variable 'snapshot_id' referenced before assignment

- boa/contracts/base_evm_contract.py
- tests/unitary/test_reverts.py
Fixed https://github.com/vyperlang/titanoboa/issues/199
Copying dev reason to the parent error details
Test is included
dev reason is now propagated from child contracts so it may be used with `boa.reverts`
> feat[test]: propagate dev reason to parent stack

- boa/contracts/vyper/event.py
- tests/integration/fork/test_logs.py
Fix `TypeError: RawEvent() takes no arguments` occurring while retrieving logs containing unknown events.
* Add missing dataclass decorator to `RawEvent`
* Add test to check the fix
The test (`tests/integration/fork/test_logs.py`) should pass with the fix and fail without it
> fix creation of RawEvents

- boa/environment.py
- boa/network.py
- boa/vm/fork.py
- boa/vm/py_evm.py
- tests/unitary/test_fork_utils.py
> feat[fork]: add set_code, get_storage, set_storage to boa.env

- .github/workflows/integration.yaml
- boa/contracts/base_evm_contract.py
- boa/network.py
- boa/test/plugin.py
- tests/integration/fork/test_logs.py
Fixes #202
Tested in https://github.com/DanielSchiavini/titanoboa/actions/runs/9029296510/job/24811369660?pr=7 via https://github.com/DanielSchiavini/titanoboa/pull/7
> fix[test] integration tests

- README.md
- boa/integrations/jupyter/jupyter.js
- docs/source/testing.rst
- examples/jupyter_browser_signer.ipynb
Fixes #197
- Add a better error message when backend cannot be reached
- Update documentation explaining how to install the jupyter plugin
- Set the output to show an error message, when an element is available
- Otherwise, show the message in a JS prompt
When running the plugin without the backend extension installed the following error is displayed:
- better errors when jupyter plugin is not installed
> feat: error when jupyter plugin is not installed

- boa/interpret.py
Patch inconsistency of `vyper-0.4.0` branch with new vyper version `0.4.0.rc5`.
In vyper the `FileInput` no longer has a `source_code` field:
https://github.com/vyperlang/vyper/blob/75c75c5631222dd1b98c23f8cfeedc080e47a9e3/vyper/compiler/input_bundle.py#L37-L40
I used the contents field.
Use this example https://github.com/ritzdorf/titanoboa/?tab=readme-ov-file#basic 
It did no longer work.
Adjust `FileInput` usage to match updated `vyper` definition
> Update FileInput to match vyper-0.4.0.rc5

- boa/network.py
- pyproject.toml
A new version of eth-account released on May 20th has broken our code.
- We are getting the error `'SignedTransaction' object has no attribute 'rawTransaction'` ([example](https://github.com/DanielSchiavini/titanoboa-zksync/actions/runs/9170771752/job/25213666344#step:5:852))
- `rawTransaction` was deprecated in [release 0.12](https://eth-account.readthedocs.io/en/latest/release_notes.html#eth-account-v0-12-0-2024-04-01): https://github.com/ethereum/eth-account/pull/266
- now it was removed in [release 0.13](https://eth-account.readthedocs.io/en/latest/release_notes.html#eth-account-v0-13-0-2024-05-20): https://github.com/ethereum/eth-account/pull/268
- Renamed rawTransaction to raw_transaction
- Updated the requirements list
- Tests should pass
- Updated eth-account to 0.13
> chore: Update eth-account

- boa/util/disk_cache.py
apparently with xdist, multiple processes can allocate the same thread id
> fix race in disk cache

- boa/util/disk_cache.py
When errors occur during the contract compilation, we currently get:
```
FileNotFoundError: [Errno 2] No such file or directory: '...'
During handling of the above exception, another exception occurred: ...
```
This PR should change the stack to show the real issue.
> fix: confusing stack trace

- boa/interpret.py
- tests/unitary/utils/test_cache.py
that could lead to confusing error messages in case a contract is deployed twice with the same source code.
- add contact name to cache key
- The cache should not return the same object when the contract name is different.
- fix: cache should be ignored when compiling with a different contract name
> fix[cache]: add contract name to cache key

- boa/vm/fork.py
- boa/vm/py_evm.py
- tests/integration/fork/conftest.py
- tests/integration/fork/test_from_etherscan.py
Fix the prefetch fork state
- Fixed the `is_forked` property of PyEVM class
- Avoid locked changes, use commit instead
- Added tests
Test are included
- fix: prefetch state checks
> fix: prefetch state checks

- boa/integrations/jupyter/browser.py
- boa/integrations/jupyter/jupyter.js
- boa/integrations/jupyter/utils.py
- Added a switch that allows the user to switch on debug logging in google colab
- User may change the `BrowserRPC.debug_mode` variable or via env `boa.env._rpc.debug_mode = True`
- Browser should display all the communication between the wallet and boa
- feat: implement debug mode switch for colab
> feat: implement debug mode switch for colab

- boa/contracts/vyper/vyper_contract.py
- tests/unitary/test_logs.py
- tests/unitary/test_reverts.py
This PR is similar to https://github.com/vyperlang/titanoboa/pull/228 however it targets the 0.4.0 branch. Vyper >=0.4.0-rc4 also has source maps for constructors (since https://github.com/vyperlang/vyper/pull/4008).
- Fix and test exceptions during contract construction
- Use 'assembly' instead of 'assembly_runtime' source map during the constructor
- Add tests
- Tests are included
- reverts in constructors have proper stack traces
> feat: handle constructor stack trace (vyper 0.4)

- pyproject.toml
- tests/unitary/jupyter/test_browser.py
- Create an optional dependency so users can easily use boa in colab
- Add a new optional dependency to ipykernel>6 when running in colab
- Run `!pip install "titanoboa[colab] @ git+https://github.com/vyperlang/titanoboa.git@8293f1235"` in colab, `CurveStableSwapNGViews` should compile properly
- [Example notebook](https://colab.research.google.com/drive/1CxQ2URRf3AjRkKxd83u3fyJzzWAXlDpe?usp=sharing)
- Create an optional dependency so users can easily use boa in colab
> fix[colab]: add optional dependency

- .gitignore
- boa/profiling.py
update view; arrange profiling table on median and not mean (so users can ignore storage slot writes and look at computations instead)
call profile column looks like the following:
1. one less column (no address column. it's all in column 1)
2. paths are shorter
3. values are arranged based on median gas costs and not average gas costs
profiling table looks like:
1. paths are shorter
2. values are arranged based on median gas costs
arranging by median means storage reads and writes do not populate the top of the table. this is much better when it comes to looking for computations to optimise.
very simple code changes
run a profiling test
improve profiling table view and arrange data by median gas costs
> improve profiling output

- boa/contracts/vyper/vyper_contract.py
- examples/ERC20.vy
- tests/unitary/fixtures/module_contract.vy
- tests/unitary/fixtures/module_lib.vy
- tests/unitary/test_modules.py
Fixes #252
- Fixed KeyError
- By ignoring the debug frames of library errors
- Test is included
N/A
> Fix KeyError when error happens in library

- README.md
Adjusted the documentation to reflect the proper way to use network mode
Tried what was in the readme, failed, looked through the titanoboa codebase, looked at the eth_account documentation, and then tested this
Run that very example
docs: correct network mode usage
> docs: correct network mode usage

- boa/coverage.py
- boa/environment.py
- boa/interpret.py
regressions introduced in vyper-0.4.0 upgrade and zksync plugin refactor (2a0065d652)
> fix: coverage

- boa/explorer.py
- Updated the expected rate limit message
- Ethercan can return one of:
- `{'status': '0', 'message': 'NOTOK', 'result': 'Max calls per sec rate limit reached (X/sec)'}` [example](https://github.com/vyperlang/titanoboa/actions/runs/10575632325/job/29299683807?pr=182#step:7:129)
- `{'status': '0', 'message': 'NOTOK', 'result': 'Max rate limit reached'}` (existing code)
- `{'status': '0', 'message': 'NOTOK', 'result': 'Max rate limit reached, please use API Key for higher rate limit'}` ([reference](https://docs.etherscan.io/support/common-error-messages))
- Checking the status of the response
- Checking the error message
> fix: update expected Etherscan message

- boa/explorer.py
> feat: add exponential backoff factor for etherscan

- boa/__init__.py
- boa/dealer.py
- tests/unitary/test_deal.py
Added a way to manipulate the most common implementations of ERC20 tokens balance.
This code traces SLOAD operations to find the storage slot containing an ERC20 token's balance for a given address. It patches the SLOAD opcode, records accessed slots during a balanceOf call, then identifies the correct slot by comparing values.
Unit tests
> feat: deal cheatcode

- boa/contracts/vyper/vyper_contract.py
- tests/unitary/contracts/vyper/test_vyper_contract.py
in this case, is_error is not set, so marshal_to_python tries to decode non-existent return value. this inspects `computation.beneficiaries` to check if a selfdestruct happened.
credit @Leminkay for triage and diagnosis of the bug.
fix #269
> fix: handling of selfdestruct

- boa/contracts/abi/abi_contract.py
- boa/contracts/base_evm_contract.py
- boa/contracts/call_trace.py
- boa/contracts/vyper/vyper_contract.py
- boa/vm/py_evm.py
- tests/integration/fork/test_abi_contract.py
- tests/unitary/contracts/abi/test_abi.py
- tests/unitary/test_reverts.py
print call trees on error
fix some bugs (related to modules, printing errors)
> feat: print call trees on error

- boa/integrations/jupyter/jupyter.js
- Fixed 2 issues that were raised by merge conflicts and incorrectly solved
- The `config` object was introduced in https://github.com/vyperlang/titanoboa/commit/6c4524677381200054f502ccb4f53692238a5ff0, but commit [517e7df](https://github.com/vyperlang/titanoboa/commit/517e7df49140482e860c74d893e9cd0394913e42#diff-182fd90cef1fb2af67209a24706164d38020e4a61d6b696d3cc7ee1e99183d73R88) missed this
- The functions `loadSigner` and `sendTransaction` were deleted in [9307ce90](https://github.com/vyperlang/titanoboa/pull/174/commits/9307ce90c8c5d7ad20502ea5e2be653bc9105c56#diff-182fd90cef1fb2af67209a24706164d38020e4a61d6b696d3cc7ee1e99183d73) but then mistakenly reintroduced in the merge commit [bbd1a6](https://github.com/vyperlang/titanoboa/pull/174/commits/bbd1a61425e7f7f6234c2a59fe6859e3a2065c …
> fix: merge conflict issue in jupyter integration

- boa/verifiers.py
@AlbertoCentonze tried to verfiy a contract with boa. The contract could be found in `/smart-contracts` API call, but misses the `is_verified` field. This PR should add a check to make sure the contract is actually verified.
I'm trying to contact Blockscout devs to check what's going on in this case, given the verification via UI worked fine.
> fix[verify]: check whether the contract is really verified

- boa/contracts/vyper/vyper_contract.py
- boa/deployments.py
- boa/network.py
- boa/util/open_ctx.py
- boa/verifiers.py
- tests/integration/network/anvil/conftest.py
- tests/integration/network/anvil/test_network_env.py
- tests/integration/network/sepolia/conftest.py
- tests/integration/network/sepolia/test_sepolia_env.py
> feat(draft): add deployment logs to network mode

- boa/deployments.py
- boa/network.py
- tests/integration/network/anvil/test_network_env.py
- tests/integration/network/sepolia/test_sepolia_env.py
> feat: add abi column to deployments

- boa/__init__.py
- boa/interpret.py
- tests/unitary/contracts/vyper/test_vyi.py
create an ABIContractFactory from a vyi file
> feat: add load_vyi and loads_vyi

- boa/__init__.py
- tests/unitary/test_boa.py
- Use the `Open` helper in `set_env`
- Refactor other methods to use `set_env` instead of `_env_mgr` as they became the same
> feat: have set_env return a context manager

- boa/contracts/vvm/vvm_contract.py
- tests/unitary/contracts/vvm/test_vvm.py
Passing kwargs when deploying from vvm deployer.
Unit tests.
Passing kwargs when deploying from vvm deployer.
> feat: vvm deployer forward kwargs

- CONTRIBUTING.md
- boa/deployments.py
- boa/network.py
- tests/integration/network/anvil/test_network_env.py
add a `filename` column to the database
```python
class DeploymentsDB:
def __init__(self, path=":memory:"):
if path != ":memory:":  # sqlite magic path
path = Path(path)
path.parent.mkdir(parents=True, exist_ok=True)
self.db = sqlite3.connect(path)
self.db.execute(_CREATE_CMD)
if not self._filename_is_in_db():
try:
self.db.execute("ALTER TABLE deployments ADD COLUMN filename text;")
self.db.commit()
except sqlite3.Error as e:
self.db.rollback()
raise Exception(f"Failed to add 'filename' column: {e}")
```
You can run the test I created:
```bash
pytest -k test_deployments_db_migration
```
- feat: Added migration for databases without the filename column
> feat: add filename to deployments db

- CONTRIBUTING.md
prefer `git commit` without `-m` as it forces you to think about the commit message. `git add .` is also a bit dangerous since you can accidentally add files you did not mean to add. `git commit -a` rather only adds changes tracked files.
> docs: simplify commit instruction

- boa/vm/py_evm.py
- tests/integration/fork/test_block_variables.py
- tests/unitary/jupyter/test_browser.py
Added the ability to access real `block.prevhash` as well as `blockhash(block.number - 1)` from vyper contracts.
Implemented simple tests to validate functionality, and some neighboring tests
Added the following lines to `boa/vm/py_evm.py
`:
```
self.patch.prev_hashes = [bytes.fromhex("0"* 32)] * 255  # placeholder not to fetch all prev hashes
self.patch.prev_hashes[0] = bytes.fromhex(block_info["parentHash"][2:]) # this one we fetched
```
Run the following test command:
`pytest tests/integration/fork/test_block_variables.py -s
`
Added support for accessing block.prevhash and blockhash(block.number - 1)
```
/\_/\  
( o.o )  
(> ♡ <)  
```
> feat: prevhash in forked environment

- docs/template.md
excluded template file from search
try search for "template"
> docs: exclude template file from search

- boa/contracts/abi/abi_contract.py
- boa/contracts/base_evm_contract.py
- boa/contracts/vvm/vvm_contract.py
- boa/contracts/vyper/event.py
- boa/contracts/vyper/vyper_contract.py
- boa/interpret.py
- boa/util/disk_cache.py
- tests/integration/fork/test_logs_fork.py
- tests/unitary/contracts/vvm/test_vvm.py
- tests/unitary/utils/test_cache.py
- add namedtuple decoding for VVMContract structs
- also namedtuple decoding for VVMContract events
- IMPORTANT: this is different than the existing get_logs API (for VyperContract). probably VyperContract should have the namedtuple decoding for get_logs as well
- add `handle_error()` in VVMDeployer.deploy() to properly raise BoaErrors that occur in the ctor
> feat: namedtuple decoding for vvmcontract structs

- boa/contracts/vvm/vvm_contract.py
ensure _computation is set properly after VVMContract.deploy is run
> fix: add _computation after VVMContract.deploy

- boa/environment.py
- docs/api/env/env.md
- tests/unitary/test_env_timestamp.py
Added a `boa.env.timestamp()` shortcut to improve devex, also documented it properly.
As per title.
S <- a tiny snake
> feat: add `env.timestamp` shortcut

- boa/contracts/vvm/vvm_contract.py
- boa/contracts/vyper/vyper_contract.py
- boa/util/eip1167.py
- boa/vm/py_evm.py
- tests/unitary/test_blueprints.py
- tests/unitary/test_minimal_proxy.py
fix minimal proxy registration in titanoboa_computation.apply_create_message
fix stack traces for minimal proxies
add tests for blueprint registration
> fix: minimal proxy stack traces

- boa/contracts/vyper/vyper_contract.py
- boa/vm/py_evm.py
- tests/unitary/contracts/vyper/test_vyper_contract.py
.get() was broken for HashMaps. there were two regressions, one is the type of the storage variable model address needed to be updated to the newer `Address` type. the other was that the order of preimage to image mapping was reversed in 59a78dddb2fa3662b during a larger refactor.
additionally, unit tests have been added to prevent future regressions
> fix regression in HashMap.get()

- boa/contracts/vyper/compiler_utils.py
- boa/interpret.py
- pyproject.toml
- tests/unitary/contracts/vyper/test_vyper_contract.py
- tests/unitary/test_logs.py
- tests/unitary/test_modules.py
- tests/unitary/utils/test_cache.py
- update calls to analyze_module since import resolution is now a separate step (vyperlang/vyper#4229)
- add no_vvm= kwarg to loads and loads_partial (to avoid using vvm)
- fn_ast.args.node_source_code no longer works after ASTTokens refactor (vyperlang/vyper#4364), so something had to be handrolled
- some equality-based unit tests no longer work (probably after removing recursive `VyperNode.__eq__()` implementation, vyperlang/vyper#4433)
> add support for vyper 0.4.1

- boa/profiling.py
fix gas profiling -- the current machinery would ignore pcs which are not in pc_raw_ast_map. however, this is not correct since pc_raw_ast_map is sparse (in pcs). this commit propagates the node from pc_raw_ast_map until it changes.
> fix: gas profiling

- boa/contracts/vyper/vyper_contract.py
- boa/interpret.py
the source map is not shared between VyperContract instances since it is not cached on CompilerData. this computes it before putting it into the disk cache.
> fix[perf]: fix performance issue in computing source map

- docs/api/common_classes/address.md
- docs/api/common_classes/deployer.md
- docs/api/env/env.md
- docs/api/pyevm/deregister_precompile.md
- docs/api/pyevm/register_precompile.md
also update Address and ComputationAPI docs
> docs: update precompile docs

- .gitignore
- boa/explorer.py
- boa/interpret.py
- boa/verifiers.py
- tests/integration/fork/test_from_etherscan.py
- tests/integration/network/sepolia/test_sepolia_env.py
- #403 
- #375
---
Enhancing compatibility with Etherscan by migrating to Etherscan API v2.
* **Etherscan API v2 Migration**: Updated the default Etherscan URI to use the v2 endpoint and switched from using `data` payloads to query parameters for contract verification requests. Added support for `chain_id` in multiple methods to align with the new API requirements.
* **Etherscan verifier**: Updated integration tests to reflect the migration to Etherscan API v2. 
- `abi = etherscan.fetch_abi(addr, chain_id=Env.get_singleton().evm.patch.chain_id)` in `interpret.py` better way?
Run the following test pytest:
```
pytest tests/integration/network/sepolia/test_sepolia_env.py -vvv -k test_verify
```
Should pass for Etherscan not Blockscout.
Tests not passing (unrelated or need help):
- …
> feat: add Etherscanv2 API Explorer support
